### ISSUE TITLE
It would be nice if js bakery could be updated with fixes for multi-caveat discharge and available on npm registry

### ISSUE THREAD

**Issue by urosj** [juju/bakeryjs#2]

**Comment by hatched** [comment]
Yeah we need to update it to support the macaroon v2 as well.

This version is currently on NPM however: https://www.npmjs.com/package/macaroon-bakery

**Comment by hatched** [comment]
After some investigation it turns out that we already did update it to the latest macaroon js which supports v2 and multi-caveat discharges.
