### ISSUE TITLE
callback not being called in case of TLS cert error in bakery request

### ISSUE THREAD

**Issue by albertodonato** [juju/bakeryjs#5]
When bakery tries to discharge a 3rd party caveat to an https endpoint whose certificate is not trusted (e.g. self-signed), the `POST /discharge` fails, but the error is not propagated to the caller's callback as it doesn't contain a JSON text in the body (IOW, `JSON.parse()` fails).

As a side note, it would be nice if the returned error could always be a string, so that the caller can use it for user feedback.

**Comment by squidsoup** [comment]
This also occurs in the case of just a 500. It appears, `_getThirdPartyDischarge` fails to receive an error object on a 500 and proceeds to parse a failed response, passing undefined instead of a macaroon object into `macaroonlib.importMacaroons`.

```
macaroon.js:962 Uncaught TypeError: Cannot read property 'signature' of undefined
    at importJSON (macaroon.js:962)
    at Object.importMacaroons (macaroon.js:953)
    at callback (index.js:323)
    at exitSuccessfully (index.js:230)
    at response (index.js:236)
    at XMLHttpRequest.handler (index.js:585)
```
